=== aibasel-teaching/krummstab/krummstab/schemas/config-shared-schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "lecture_title": {
        "type": "string",
        "minLength": 1
      },
      "assistant_email": {
        "type": "string",
        "pattern": "[^@]+@[^@]+\\.[^@]+"
      },
      "marking_mode": {
        "type": "string",
        "enum": [
          "static",
          "exercise"
        ]
      },
      "use_marks_file": {
        "type": "boolean"
      },
      "points_per": {
        "type": "string",
        "enum": [
          "sheet",
          "exercise"
        ]
      },
      "min_point_unit": {
        "type": "number",
        "exclusiveMinimum": 0
      },
      "max_team_size": {
        "type": "integer",
        "minimum": 1
      },
      "classes": {
        "type": "object",
        "additionalProperties": {
          "type": "array",
          "items": {
            "type": "array",
            "items": {
              "type": "array",
              "items": [
                {
                  "type": "string",
                  "minLength": 1
                },
                {
                  "type": "string",
                  "minLength": 1
                },
                {
                  "type": "string",
                  "pattern": "[^@]+@[^@]+\\.[^@]+"
                }
              ],
              "minItems": 3,
              "maxItems": 3
            }
          }
        }
      },
      "tutor_list": {
        "type": "array",
        "items": {
          "type": "string",
          "minLength": 1
        }
      },
      "teams": {
        "type": "array",
        "items": {
          "type": "array",
          "items": {
            "type": "array",
            "items": [
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "string",
                "minLength": 1
              },
              {
                "type": "string",
                "pattern": "[^@]+@[^@]+\\.[^@]+"
              }
            ],
            "minItems": 3,
            "maxItems": 3
          }
        }
      }
    },
    "required": [
        "lecture_title",
        "marking_mode",
        "use_marks_file",
        "points_per",
        "min_point_unit",
        "max_team_size"
      ],
    "if": {
      "properties": {
        "marking_mode": { "const": "static" }
      }
    },
    "then": {
      "required": ["classes"]
    },
    "else": {
      "required": ["tutor_list", "teams"]
    }
}

=== aibasel-teaching/krummstab/tests/config-shared-exercise.json
{
    "lecture_title": "Foundations of Artificial Intelligence",
    "assistant_email": "florian.pommerening@unibas.ch",
    "marking_mode": "exercise",
    "use_marks_file": true,
    "points_per": "exercise",
    "min_point_unit": 0.5,
    "tutor_list": [ "tamara", "tatiana", "terence" ],
    "max_team_size": 3,
    "teams": [
        [
            ["Salom√©", "Schmid", "salome.schmid@stud.unibas.ch"],
            ["Samira", "Studer", "samira.studer@stud.unibas.ch"],
            ["Silvan", "Stucki", "silvan.stucki@stud.unibas.ch"]
        ],
        [
            ["Sabine", "Sommer", "sabine.sommer@stud.unibas.ch"]
        ],
        [
            ["Sandro", "Schenk", "sandro.schenk@stud.unibas.ch"],
            ["Samuel", "Seiler", "samuel.seiler@stud.unibas.ch"]
        ]
    ]
}

=== aibasel-teaching/krummstab/tests/config-shared-static.json
{
    "lecture_title": "Foundations of Artificial Intelligence",
    "assistant_email": "florian.pommerening@unibas.ch",
    "marking_mode": "static",
    "use_marks_file": true,
    "points_per": "sheet",
    "min_point_unit": 0.5,
    "max_team_size": 3,
    "classes": {
        "tamara": [
            [
                ["Sabine", "Sommer", "sabine.sommer@stud.unibas.ch"]
            ]
        ],
        "tatiana": [
            [
                ["Salom√©", "Schmid", "salome.schmid@stud.unibas.ch"],
                ["Samira", "Studer", "samira.studer@stud.unibas.ch"],
                ["Silvan", "Stucki", "silvan.stucki@stud.unibas.ch"]
            ]
        ],
        "terence": [
            [
                ["Sandro", "Schenk", "sandro.schenk@stud.unibas.ch"],
                ["Samuel", "Seiler", "samuel.seiler@stud.unibas.ch"]
            ]
        ]
    }
}
