=== aibasel-teaching/krummstab/krummstab/schemas/config-individual-schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "tutor_name": {
        "type": "string",
        "minLength": 1
      },
      "tutor_email": {
        "type": "string",
        "pattern": "[^@]+@[^@]+\\.[^@]+"
      },
      "email_signature": {
        "type": "string"
      },
      "feedback_email_cc": {
        "type": "array",
        "items": {
          "type": "string",
          "pattern": "[^@]+@[^@]+\\.[^@]+"
        }
      },
      "smtp_url": {
        "type": "string"
      },
      "smtp_port": {
        "type": "integer"
      },
      "smtp_user": {
        "type": "string"
      },
      "ignore_feedback_suffix": {
        "type": "array",
        "items": {
          "type": "string",
          "pattern": "^\\.",
          "minLength": 2
        }
      }
    },
    "required": [
      "tutor_name"
    ]
}

=== aibasel-teaching/krummstab/tests/config-individual.json
{
    "tutor_name": "PLACEHOLDER_NAME",
    "tutor_email": "tatiana.tutor@unibas.ch",
    "feedback_email_cc": [ "tamara.tutor@unibas.ch", "tatiana.tutor@unibas.ch", "terence.tutor@unibas.ch" ],
    "smtp_url": "smtp-ext.unibas.ch",
    "smtp_port": 587,
    "smtp_user": "tuttat00",
    "ignore_feedback_suffix": [ ".xopp" ]
}
